Aichat_v2/Aichat/urls.py
from django.urls import path,include
from apps.chat import views
from apps.infer import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',views.index,name='index'),
    path('chat/', include("apps.chat.urls")),
    path('infer/', include("apps.infer.urls"))
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns.append(path("__debug__/",include(debug_toolbar.urls)))

Aichat_v2/apps/chat/urls.py
#encoding: utf-8
from django.urls import path
from . import views

app_name = 'chat'

# urlpatterns = [
#     path('<int:news_id>/',views.news_detail,name='news_detail'),
#     path('list/',views.news_list,name='news_list'),
#     path('public_comment/',views.public_comment,name='public_comment')
# ]

urlpatterns = [
    path('',views.index,name='index'),
    path('response/',views.response,name='response'),
]

Aichat_v2/apps/infer/urls.py
#encoding: utf-8
from django.urls import path
from . import views

app_name = 'infer'

urlpatterns = [
    path('',views.index,name='index'),
    path('add_args/',views.add_args,name='add_args'),
    path('add_infers/',views.add_infers,name='add_infers'),
    path('add_args2/',views.add_args2,name='add_args2'),
    path('delete_infers/',views.delete_infers,name='delete_infers'),
    path('begain_infers/',views.begain_infers,name='begain_infers'),
    path('download/',views.download,name='download'),
]

Aichat_v2/apps/infer/models.py
from django.db import models

class Infer(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200)
    file = models.CharField(max_length=200)
    type = models.CharField(max_length=200)
    prompt = models.CharField(max_length=200)
    thread=models.CharField(max_length=200)
    create_time = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=200)
    result = models.CharField(max_length=200)
    class Meta:
        ordering = ['-create_time']

class Llmodel(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200)

class Textname(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200)
class Thread(models.Model):
    id = models.AutoField(primary_key=True)
    num = models.CharField(max_length=200)


Aichat_v2/apps/infer/views.py
from django.shortcuts import render,redirect,reverse
from django.conf import settings
from django.http import HttpResponse
from apps.utils import restful
from django.http import HttpResponseRedirect
from .models import Infer,Llmodel,Thread,Textname
from django.http import Http404
import requests
import json
from django.db.models import Q
import os
from django.http import StreamingHttpResponse


def save_file(file,path):
    with open(path, 'wb') as fp:
        for chunk in file.chunks():
            fp.write(chunk)

def index(request):
    infers = Infer.objects.all()
    text_files=Textname.objects.all()
    models=Llmodel.objects.all()
    threads=Thread.objects.all()
    print(infers)
    args={'models':('文心一言','chatgpt'),
             'text_files':('测试集1','测试集2'),
             'types':('common', 'greed'),
             'prompt_types':('safe', 'unsafe'),
             'thread_nums':(4,10,20),
             'parameters':('模型','测试集','线程数量')
    }
    return render(request,'infer.html',context={'infers':infers,'text_files':text_files,'args':args,'models':models
                                                ,'threads':threads})


def add_args(request):
    parameter = request.POST.get('parameter')
    content = request.POST.get('content')
    print(parameter)
    if parameter=='模型':
        models=list(Llmodel.objects.values_list('name',flat=True))
        if content not in models:
            table=Llmodel(name=content)
            table.save()
            return restful.result(data='已添加')
        else:
            return restful.result(data='请不要重复添加')
    elif parameter=='线程数量':
        threads = list(Thread.objects.values_list('num', flat=True))
        if content not in threads:
            table = Thread(num=content)
            table.save()
            return restful.result(data='已添加')
        else:
            return restful.result(data='请不要重复添加')
    else:
        print('111')
        myfile = request.FILES.get('myfile')
        filename=myfile.name
        print(filename)
        path = os.path.join(settings.MEDIA_ROOT, 'test', filename + '.txt')
        save_file(myfile,path)
        return HttpResponse('success')

def add_args2(request):
    myfile = request.FILES.get('myfile',None)
    filename = myfile.name
    print(filename)
    path = os.path.join(settings.MEDIA_ROOT, 'test', filename)
    save_file(myfile, path)
    table = Textname(name=filename)
    table.save()
    return HttpResponse('success')


API_KEY = "1VLWqnMDoqBfPufA5t8FXSbr"
SECRET_KEY = "WUYXFIuyD8e38lXNFxkYDwECsvo5ymvc"

def main(query):
    url = "https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/eb-instant?access_token=" + get_access_token()
    # 注意message必须是奇数条
    payload = json.dumps({
        "messages": [
            {
                "role": "user",
                "content": query
            }
        ]
    })
    headers = {
        'Content-Type': 'application/json'
    }

    response = requests.request("POST", url, headers=headers, data=payload)

    print(response.text)
    return json.loads(response.text)['result']
def get_access_token():
    """
    使用 AK，SK 生成鉴权签名（Access Token）
    :return: access_token，或是None(如果错误)
    """
    url = "https://aip.baidubce.com/oauth/2.0/token"
    params = {"grant_type": "client_credentials", "client_id": API_KEY, "client_secret": SECRET_KEY}
    return str(requests.post(url, params=params).json().get("access_token"))

def begain_infers(request):
    id = request.POST.get('infer_id')
    infer=Infer.objects.get(id=id)
    file=infer.file
    path=os.path.join(settings.MEDIA_ROOT,'test',file+'.txt')
    result_path=os.path.join(settings.MEDIA_ROOT,'result',id+'.json')
    if os.path.exists(result_path):
        os.remove(result_path)
    print(path)
    infer = Infer.objects.get(id=id)
    with open(path, 'r', encoding='utf-8') as fd:
        contents=fd.readlines()
        lengs=len(contents)
        for i in range(lengs):
            print(contents[i])
            data=json.loads(contents[i])
            print(data)
            infer.status=str(round((i+1)/lengs)*100)+'%'
            infer.save()
            prompt=data['prompt']
            response = main(prompt)
            print(response)
            with open(result_path, 'a+', encoding='utf-8') as fd2:
                dicts = dict(prompt=prompt, response=response)
                fd2.write(json.dumps(dicts,ensure_ascii=False))
                fd2.write('\n')
    return restful.result(data='完成')

def add_infers(request):
    name = request.POST.get('name')
    file = request.POST.get('file')
    type = request.POST.get('type')
    prompt = request.POST.get('prompt')
    status = request.POST.get('status')
    thread = request.POST.get('thread')
    print(name)
    if Infer.objects.filter(Q(name=name) & Q(file=file)):
        return restful.result(data='请勿重复提交任务')
    else:
        table=Infer(name=name,file=file,type=type,prompt=prompt,status=status,thread=thread)
        table.save()
        return restful.result(data='已添加')

def delete_infers(request):
    id = request.POST.get('infer_id')
    infer=Infer.objects.get(id=id)
    infer.delete()
    return restful.result(data='已删除')

def change_status(request):
    id = request.POST.get('infer_id')
    infer=Infer.objects.get(id=id)
    infer.status = '等待中...'
    infer.save()
    return restful.result(data='已更新')

def download(request):
    id = request.POST.get('orderid')
    # infer = Infer.objects.get(id=id)
    # id = request.POST.get('infer_id')
    print(id)
    file_name = id+'.json'
    result_path = os.path.join(settings.MEDIA_ROOT,'result',file_name)
    file = open(result_path, 'rb')
    response = StreamingHttpResponse(file)
    response['Content-Type'] = 'application/octet-stream'
    response['Content-Disposition'] = 'attachment;filename="{}"'.format(file_name.encode('utf-8').decode('ISO-8859-1'))
    return response

Aichat_v2/front/templates/aichat.html
{% load my_filter %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>smile</title>
    <script src="{% static 'js/jquery-3.3.1.min.js'%}"></script>
    <script src="{% static 'js/aichatajax.min.js'%}"></script>
    <link rel="stylesheet" href="{% static 'css/aichat.min.css' %}">
    <script src="{% static 'js/aichat.min.js' %}"></script>
</head>
<body>
{#    <header class="header">#}
{#        <div class="container">#}
{#        </div>#}
{#    </header>#}
    <nav>
        <ul class="nav">
            <li><a href="{% url 'chat:index' %}">首页</a></li>
            <li><a href="{% url 'infer:index' %}">推理</a></li>
        </ul>
    </nav>
    <div class="main">
        <div class="wrapper">
            <div class="main-content-wrapper">
                <div class="news-wrapper">
                    <div class="model-choice">
                        <form action="">
                        模型名称：
                        <select id="model_select">
                        {% for model in models %}
                            <option id="model_name">{{ model }}</option>
                        {% endfor %}
                        </select>
                    </form>
                    </div>
                    <div class="prompt-choice">
                        <form action="">
                        prompt：
                        <select id="prompt_select">
                        {% for prompt in prompts %}
                            <option id="prompt_name">{{ prompt }}</option>
                        {% endfor %}
                        </select>
                    </form>
                    </div>
                </div>
            </div>
            <div class="sidebar-wrapper">
                <div class="modle-wrapper">
                    <h1 class="title" id="model_title">{{ models.0 }}</h1>
                </div>
                <div class="prompt-wrapper">
                    <h3 class="title">prompt:</h3>
                    <textarea name="prompt-text" class="prompt-textarea" placeholder="请输入～">{{ prompts.0 }}</textarea>
                </div>
                <div class="text-wrapper">
                    <textarea name="query" class="comment-textarea" placeholder="请输入问题～" ></textarea>
                    <div class="submit-btn-group">
                        <button class="submit-btn">发送</button>
                    </div>
                </div>
                <div class="response-wrapper">
                    <p class="response-content">1</p>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

Aichat_v2/front/templates/infer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>smile</title>
    <script src="{% static 'js/jquery-3.3.1.min.js'%}"></script>
    <script src="{% static 'js/aichatajax.min.js'%}"></script>
    <link rel="stylesheet" href="{% static 'css/infer.min.css' %}">
    <script src="{% static 'js/infer.min.js' %}"></script>
{#    <script src="{% static 'js/datatables.min.js' %}"></script>#}
</head>
<body>
<nav>
    <ul class="nav">
        <li><a href="{% url 'chat:index' %}">首页</a></li>
        <li><a href="{% url 'infer:index' %}">推理</a></li>
    </ul>
</nav>
<nav>
    <ul class="nav2">
        <li class="parameter-choice">
            <div class="model-choice">
                        <form action="">
                        模型：
                        <select id="model_select">
                        {% for model in models %}
                            <option id="model_name">{{ model.name }}</option>
                        {% endfor %}
                        </select>
                    </form>
            </div>
            <div class="text-choice">
                <form action="">
                    测试集：
                    <select id="text_select">
                        {% for text_file in text_files %}
                            <option id="text_file">{{ text_file.name }}</option>
                        {% endfor %}
                    </select>
                </form>
            </div>
            <div class="type-choice">
                <form action="">
                    类别：
                    <select id="type_select">
                        {% for type in args.types %}
                            <option id="type">{{ type }}</option>
                        {% endfor %}
                    </select>
                </form>
            </div>
            <div class="prompt-choice">
                <form action="">
                    prompt：
                    <select id="prompt_select">
                        {% for prompt_type in args.prompt_types %}
                            <option id="prompt">{{ prompt_type }}</option>
                        {% endfor %}
                    </select>
                </form>
            </div>
            <div class="thread-choice">
                <form action="">
                    线程数量：
                    <select id="thread_select">
                        {% for thread in threads %}
                            <option id="thread">{{ thread.num }}</option>
                        {% endfor %}
                    </select>
                </form>
            </div>
            <div class="send-args">
                <button class="submit-args-btn">发送</button>
            </div>
            <div class="parameters-choice">
                <form action="">
                    新增参数：
                    <select id="parameters_select">
                        {% for parameter in args.parameters %}
                            <option id="parameter">{{ parameter }}</option>
                        {% endfor %}
                    </select>
                </form>
            </div>
            <div class="input-args">
                <input id='input-content' type="text" value="" size="10" Maxlength="100">
            </div>
            <div class="input-args2">
                <form id="uploadForm" action="/infer/add_args2/" method="post" enctype="multipart/form-data">
                    <input type="file" name="myfile">
                    <input type="submit" name="提交">
                </form>
            </div>
            <div class="send-config">
                <button class="submit-config-btn">提交</button>
            </div>
        </li>
    </ul>
</nav>
<table id="infers">
        <thead>
            <tr>
                <th>序号</th>
                <th>模型名称</th>
                <th>测试集</th>
                <th>时间</th>
                <th>状态</th>
                <th>开始任务</th>
                <th>删除任务</th>
                <th>下载</th>
            </tr>
        </thead>
        <tbody>
            {% for infer in infers %}
                <tr>
                    <td>{{ infer.id }}</td>
                    <td>{{ infer.name }}</td>
                    <td>{{ infer.file }}</td>
                    <td>{{ infer.create_time }}</td>
                    <td infer-id="{{ infer.id }}">{{ infer.status }}</td>
                    <td><button class="btn btn-danger btn-xs begain-btn" infer-id="{{ infer.id }}">开始</button></td>
                    <td><button class="btn btn-danger btn-xs delete-btn" infer-id="{{ infer.id }}">删除</button></td>
{#                    <td><button class="btn btn-danger btn-xs download-btn" infer-id="{{ infer.id }}">下载</button></td>#}
                    <td><form action="/infer/download/" method="post" >
                        <input type="hidden" name='orderid' value={{ infer.id }}>
                        <input type="submit" value="点击下载">
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>